// Canonical list of browser-free contracts. The fast runner and changed-file
// impact resolver share this list so routing cannot drift from execution.
export const FAST_CHECKS = Object.freeze([
  './check-architecture.mjs',
  './check-residential-openings.mjs',
  './check-atmosphere-contract.mjs',
  './check-environment-state.mjs',
  './check-env-night-glow.mjs',
  './check-house-diversity.mjs',
  './check-opening-detail-contract.mjs',
  './check-opening-glow-catalog.mjs',
  './check-nightlights.mjs',
  './check-village-night-glow.mjs',
  './check-threshold-life-contract.mjs',
  './check-door-motion-contract.mjs',
  './check-edge-mist.mjs',
  './check-door-occlusion-contract.mjs',
  './check-building-clearance.mjs',
  './check-cinematic-turns.mjs',
  './check-cinematic-reveal.mjs',
  './check-dof.mjs',
  './check-dancheong-contract.mjs',
  './check-plan-contract.mjs',
  './check-temple-contract.mjs',
  './check-road-contract.mjs',
  './check-surface-materials.mjs',
  './check-layout-contract.mjs',
  './check-wall-gate-contract.mjs',
  './check-wave-contract.mjs',
  './check-yard-layout-contract.mjs',
  './check-parcel-rebuild-contract.mjs',
  './check-live-edit-scheduler.mjs',
  './check-shader-warm.mjs',
  './check-shadow-framing.mjs',
  './check-directional-shadow-runtime.mjs',
  './check-lod.mjs',
  './check-citywall.mjs',
  './check-choga-roof.mjs',
  './check-roof-seams.mjs',
  './check-verification-plan.mjs',
  './check-verification-browser.mjs',
  './check-verification-runner.mjs',
  './check-advisory-lock.mjs',
  './check-worktree-contract.mjs',
  './check-worktree-cli.mjs',
]);

export const FAST_CHECK_PATHS = Object.freeze(FAST_CHECKS.map((path) => `tools/${path.slice(2)}`));
