// Canonical list of browser-free contracts. The fast runner and changed-file
// impact resolver share this list so routing cannot drift from execution.
//
// ── 게이트 대축소 (2026-08-02, 사용자 지시 "게이트들 대폭 축소하고 싶어, 이대로는 작업 진척이 안 돼") ──
// `npm run check`(커밋·CI 게이트)는 아래 CORE_CHECKS 만 돌린다: 레포를 가로지르는 **불변식**
// (계층 경계·계획 결정론·검증 러너 자기검사)만 커밋을 막는다. 나머지 기능별 수치 게이트 전체
// (FAST_CHECKS)는 `npm run check:deep` 으로 강등 — 커밋을 막지 않는 opt-in 이며, 해당 도메인을
// 만지는 라운드가 `check:pr`(영향 라우팅) 또는 개별 실행으로 돌린다. 파일은 삭제하지 않았으므로
// 언제든 개별 게이트를 계약으로 되살릴 수 있다.
export const CORE_CHECKS = Object.freeze([
  './check-architecture.mjs',
  './check-plan-contract.mjs',
  './check-verification-runner.mjs',
]);

export const FAST_CHECKS = Object.freeze([
  './check-architecture.mjs',
  './check-assembly-contract.mjs',
  './check-roof-shell.mjs',
  './check-roof-ridge.mjs',
  './check-ceiling-contract.mjs',
  './check-residential-openings.mjs',
  './check-atmosphere-contract.mjs',
  './check-celestial.mjs',
  './check-cloud-silhouette.mjs',
  './check-audio-policy.mjs',
  './check-view-lifecycle.mjs',
  './check-camera-continuity.mjs',
  './check-auxiliary-building-plan.mjs',
  './check-auxiliary-building-geometry.mjs',
  './check-environment-state.mjs',
  './check-season-ground-contract.mjs',
  './check-env-night-glow.mjs',
  './check-house-diversity.mjs',
  './check-mja-house-plan.mjs',
  './check-mja-house-integration.mjs',
  './check-opening-detail-contract.mjs',
  './check-opening-glow-catalog.mjs',
  './check-nightlight-geometry.mjs',
  './check-instance-upload.mjs',
  './check-instance-merge-immutability.mjs',
  './check-nightlights.mjs',
  './check-village-night-glow.mjs',
  './check-weather-geometry.mjs',
  './check-snow-overlay.mjs',
  './check-season-particle-size.mjs',
  './check-threshold-life-contract.mjs',
  './check-door-motion-contract.mjs',
  './check-edge-mist.mjs',
  './check-village-fog-band.mjs',
  './check-forest-canopy-atten.mjs',
  './check-scatter-tree-color.mjs',
  './check-door-occlusion-contract.mjs',
  './check-building-clearance.mjs',
  './check-ground-stone-bedding.mjs',
  './check-cinematic-turns.mjs',
  './check-cinematic-reveal.mjs',
  './check-aerial-framing.mjs',
  './check-clip-stage.mjs',
  './check-walk-solids.mjs',
  './check-walk-control.mjs',
  './check-cine-quality.mjs',
  './check-frame-clock.mjs',
  './check-dof.mjs',
  './check-roof-rank-contract.mjs',
  './check-dancheong-contract.mjs',
  './check-plan-contract.mjs',
  // Packaging P1 (2026-08-08): plan JSON schema doc ↔ measured keys, cheoma CLI smoke.
  './check-plan-schema-doc.mjs',
  './check-cli.mjs',
  './check-sijeon-contract.mjs',
  './check-sijeon-approach.mjs',
  './check-temple-contract.mjs',
  './check-road-contract.mjs',
  './check-drainage-plan.mjs',
  './check-dangsan-plan.mjs',
  './check-surface-materials.mjs',
  './check-palette-provider.mjs',
  './check-node-core.mjs',
  './check-layout-contract.mjs',
  './check-gosat-topology.mjs',
  './check-wall-gate-contract.mjs',
  './check-mud-wall-contract.mjs',
  './check-wall-step-contract.mjs',
  './check-pad-landing.mjs',
  './check-wave-contract.mjs',
  './check-yard-layout-contract.mjs',
  './check-yard-polygon-contract.mjs',
  './check-yard-proportion-contract.mjs',
  './check-yard-life-contract.mjs',
  './check-critter-contract.mjs',
  './check-parcel-rebuild-contract.mjs',
  './check-live-edit-scheduler.mjs',
  './check-live-edit-signatures.mjs',
  './check-rebuild-morph.mjs',
  './check-building-navigation.mjs',
  './check-scene-guide.mjs',
  './check-shader-warm.mjs',
  './check-hop-warm.mjs',
  './check-program-diet.mjs',
  './check-shadow-framing.mjs',
  './check-directional-shadow-runtime.mjs',
  './check-hero-sun.mjs',
  './check-rim-gate.mjs',
  './check-rim-master.mjs',
  './check-fog-wash.mjs',
  './check-pixel-stats.mjs',
  './check-palace-precinct.mjs',
  './check-lod.mjs',
  './check-citywall.mjs',
  './check-creek.mjs',
  './check-creek-bank-geometry.mjs',
  './check-choga-roof.mjs',
  './check-chimney-anchor.mjs',
  './check-glossary-plan.mjs',
  './check-roof-seams.mjs',
  './check-giwa-tile-course.mjs',
  './check-tile-look.mjs',
  './check-verification-spatial-grid.mjs',
  './check-render-budget-contract.mjs',
  './check-verification-plan.mjs',
  './check-verification-browser.mjs',
  './check-verification-runner.mjs',
  './check-advisory-lock.mjs',
  './check-worktree-contract.mjs',
  './check-worktree-cli.mjs',
  './check-credits-catalog.mjs',
]);

export const FAST_CHECK_PATHS = Object.freeze(FAST_CHECKS.map((path) => `tools/${path.slice(2)}`));
